name: Check PR Title

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - edited
      - reopened
      - labeled
      - review_requested
      - ready_for_review
      - synchronize

jobs:
  title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@91f4126c9e8625b9cadd64b02a03018fa22fc498
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}